import Head from 'next/head'
import Main from '../components/main/main'
import ModuleList from '../components/module-list/module-list'
import ModuleListItem from '../components/module-list-item/module-list-item'
import ModuleListHeading from '../components/module-list-heading/module-list-heading'

export default function Home() {
  return (
    <div>
      <Head>
        <title>HECKPAL! :)</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main>
        <ModuleListHeading>Endorphine.es</ModuleListHeading>
        <ModuleList>
          <ModuleListItem href="/endorphines/cockpit-2">Cockpit 2</ModuleListItem>
        </ModuleList>

        <ModuleListHeading>Make Noise</ModuleListHeading>
        <ModuleList>
          <ModuleListItem href="/endorphines/cockpit-2">Morphagene</ModuleListItem>
        </ModuleList>

        <ModuleListHeading>Squarp</ModuleListHeading>
        <ModuleList>
          <ModuleListItem href="/endorphines/cockpit-2">Rample</ModuleListItem>
        </ModuleList>

        <ModuleListHeading>Qu-bit</ModuleListHeading>
        <ModuleList>
          <ModuleListItem href="/qu-bit/data-bender">Cascade</ModuleListItem>
          <ModuleListItem href="/qu-bit/data-bender">Data Bender</ModuleListItem>
          <ModuleListItem href="/qu-bit/data-bender">Surface</ModuleListItem>
        </ModuleList>
      </Main>
    </div>
  )
}
